# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Kareena Shah"                                # Your name
  description: "Kareena Shah is a senior undergraduate student at Case Western Reserve University"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Dance"
        href: dance/index.qmd
      - text: "Photography"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/kareena-shah-84217b1ab/
      - icon: envelope
        aria-label: email
        href: "mailto:kareenanshah@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Kareena Shah</span>
    center: |
    right: |
      <span class="faux-block"><a href="mailto:kareenanshah@gmail.com">Contact Me</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true